#            PortalsCanceller by Volax
# Source Code: https://github.com/VolaxYT/PortalsCanceller/

portals:
  nether:
    create-portals-not-allowed-worlds: []
    enter-portals-not-allowed-worlds: []
  end:
    create-portals-not-allowed-worlds: []
    enter-portals-not-allowed-worlds: []

logs:
  console: true
  file: false

permissions:
  reload: "pc.reload"
  manage: "pc.manage"