name: PortalsCanceller
version: 1.0-alpha
main: fr.volax.portal.PortalsCanceler
description: The Ultimate Plugin to control the inter-world movement of your players
author: Volax
commands:
  portals:
    description: Main command