name: PortalsManager
version: 1.0-beta
main: fr.codemc.portals.PortalsManager
description: The Ultimate Plugin to control all the portals of all your worlds.
author: Volax
commands:
  portals:
    description: Main command of the plugin
  currentWorld:
    description: Get the world you are in